### ISSUE TITLE
Django Generator - Server Session detected in APIView and React   

### ISSUE THREAD

**Issue by app-generator** [app-generator/app-generator#369]
This is done in this PR but have conflicts. 

 https://github.com/app-generator/app-generator/pull/368

@ar-rehman135 please check. 

TY

**Comment by app-generator** [comment]
Hello @ar-rehman135 

The fix is not working. Here is the runtime log: 

The detected user is `AnonymousUser` not the authenticated user. 

Please check. Thanks. 

Pull the latest sources ... I pushed a hot fix.  

```python
[14/Dec/2024 09:38:48] "GET /tools/django-generator/design HTTP/1.1" 200 2088
Internal Server Error: /tools/django-generator-status
Traceback (most recent call last):
  File "D:\work\app-generator\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\work\app-generator\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\work\app-generator\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\work\app-generator\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\work\app-generator\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
  File "D:\work\app-generator\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\work\app-generator\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\work\app-generator\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\app-generator\apps\tool_django_generator\views.py", line 64, in post
    app.user = request.user
  File "D:\work\app-generator\env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x000001614B94F460>": "GeneratedApp.user" must be a "User" instance.    
[14/Dec/2024 09:38:57] "POST /tools/django-generator-status HTTP/1.1" 500 115929
(env) PS D:\work\app-generator> 
```

**Comment by app-generator** [comment]
This is fixed. 

@ar-rehman135 pull the latest changes.
